### ISSUE TITLE
Generate assembly for common functions

### ISSUE THREAD

**Issue by klauspost** [akualab/narray#1]
I don't know if it was always the plan, but the current library makes it very easy to create assembler optimized routines.

Here is an example of how it could be structured:

``` Go
// Div divides two narrays elementwise.
// out = in0 / in1
// If out is nil a new array is created.
func Div(out *NArray, in0, in1 *NArray) *NArray {

    if out == nil {
        out = New(in0.Shape...)
    }
    if !EqualShape(out, in0, in1) {
        panic("narrays must have equal shape.")
    }
    divSlice(out.Data, in0.Data, in1.Data)
    return out
}

// Generic function, this is quite easy to do in SSE2 for instance.
// Assumptions the assembly can make:
// out != nil, a != nil, b != nil
// len(out)  == len(a) == len(b)
func divSlice(out, a, b []float64) {
    for i := 0; i < len(out.Data); i++ {
        out[i] = a[i] / b[i]
    }
}
```

The `divSlice` function can then be assembler, which can eliminate bounds-checks, and even do multiple elements in parallel, something like this:

``` Go
func divSlice(out, a, b []float64) {
    l := len(out)
    l2 := l / 2
    for i := 0; i < l2; i++ {
                // This is of course a single instruction on SSE2
        out[i*2] = a[i*2] / b[i*2]
        out[i*2+1] = a[i*2+1] / b[i*2+1]
    }
    if l&1 == 1 {
        out[l-1] = a[l-1] / b[l-1]
    }
}
```

If I am not completely mistaking, this should make these types of operations at least an order of magnitude faster for decently sized arrays.

Is this something you are looking into, or should I dig further into this myself?

**Comment by leoneu** [comment]
Thanks! My main motivation was to have a stable API because I was getting tired of using slice of slices. My plan is to use the API in other projects and add what I need. When I get to optimization I will try to find the bottlenecks.  Of course I welcome pull requests or suggestions for adding functionality.
