### ISSUE TITLE
32 bit version

### ISSUE THREAD

**Issue by klauspost** [akualab/narray#11]
I have done a conversion of the library (without matrix functions), to have underlying 32 bit arrays. This is mainly useful for stuff where speed is more important than precision, games, image processing, etc.

Would you be interested in it, you can grab it [here](http://files.klauspost.com/array32.zip). If you don't want anything to do with it, I can just host it on my own github. But since you have made most of the work, I thought it would be fair that you should get it.

**Comment by klauspost** [comment]
I Updated the file, now with the same level of assembler as 64 bit. Speedup is approximately twice the speedup on 64 bits, since we can operate on 4 elements at once.

**Comment by leoneu** [comment]
Awesome! Any thoughts on how to integrate the 2 versions? Would be a pain
to maintain separately? Use code gen?

**Comment by klauspost** [comment]
I looked a bit at the diffs, and I think most of it can be done with codegen.

The good thing is that `v := float64(x)` is a no-op by the compiler, if `x` is already float64.

This means that this code:

``` Go
func absSlice(out, a []float32) {
    for i, v := range a {
        out[i] = float32(math.Abs(float64(v)))
    }
}
```

Can be templated to be:

``` Go
func absSlice{{.FloatTypeCap}}(out, a []{{.FloatType}}) {
    for i, v := range a {
        out[i] = {{.FloatType}}(math.Abs(float64(v)))
    }
}
```

Where `{{.FloatType}}` is float32 or float64.

Constants will have to be casted explicitly, like `sum := 0.0` should be `sum := {{.FloatType}}(0.0)`.
- [ ] `arrayfuncs.go` - trivially templated.
- [ ] `arrayfuncs_amd64.s` - not everything is easily templated. The easiest would probably be to have one file per type.
- [ ] `genarray.go` - one difference, easily templated.
- [ ] `narray.go` - has a few differences, but nothing major.
- [ ] `narray_test.go` - trivial to template.

The only real question is how to handle it. Should it be a separate package, or should we add a "NArray32" type, and keep 64 bits as "NArray"? Both have pros and cons.

**Comment by leoneu** [comment]
one option is to use one type and two packages like this:

```
narray/
            na32/
            na64/
```

which will make it easy to swap packages and run experiments to measure performance vs accuracy without having to change the types in the application code.  What do you think?

**Comment by klauspost** [comment]
Makes sense. Do you have any pending WIP changes? Otherwise, I will see if I can begin converting the code to templates.  

With 7 stars, it doesn't seem like we will be upsetting a huge number of people with the breaking change.

**Comment by leoneu** [comment]
Nothing pending, go ahead.
