### ISSUE TITLE
API differences (Add,Sub vs Div, Mul)

### ISSUE THREAD

**Issue by klauspost** [akualab/narray#5]
I was a bit surprised that:

``` Go
func Add(out *NArray, in ...*NArray) *NArray
func Sub(out *NArray, in ...*NArray) *NArray
```

('n' in arguments) didn't match:

``` Go
func Div(out *NArray, in0, in1 *NArray) *NArray 
func Mul(out *NArray, in0, in1 *NArray) *NArray
```

Shouldn't it either be one or the other?

**Comment by leoneu** [comment]
Sub and Div with multiple inputs doesn't make a lot of sense. To make it consistent I did the following. Removed Sub/Div since they can be computed using Scale/Rcp (see tests). Now we have more symmetry. Thanks!

**Comment by klauspost** [comment]
I am not sure I follow you. I could very well see a case where I would like to do:

``` Go
dst := narray.Sub(nil, a, b, c, d)
```

Where elements are subtracted in order dst = a - b - c - d

To do that, I would now have to:

``` Go
dst := narray.Add(nil, a, narray.Scale(nil, b, -1) , narray.Scale(nil, c -1) , narray.Scale(nil, d, -1))
```

(or somthing similar) It is both 'uglier' and inefficient, so I think there is a good case for re-adding Div/Sub and adding varargs to them.
